public class Student {
    private String name='Ali';
    private Integer age=15;
    private Boolean succesful= true;

    public String getName(){
        return this.name;
    }
    public Integer getAge(){
        return this.age;
    }
    
    public Boolean issuccesful(){
        return this.succesful;
    }
    
    public void setName(String Name){
        this.name=name;
    } 
    public void setAge(Integer Age){
        this.age=age;
    }
    public void setsuccesful(Boolean Succeed){
        this.succesful=succesful;
    }
   
}